name: vetas-iceland
channels:
    - conda-forge
    - defaults
dependencies:
    - python<=3.11
    - Fiona
    - gdal
    - geopandas
    - numpy
    - pandas
    - pyproj
    - pytz
    - scipy
    - Shapely
    - shutup
